version: '3'
services:
  web:
    image: prnake/Comment9
    restart: always
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
    ports:
      - '3000:3000'
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      MONGO_HOST: "mongo"
      MONGO_PORT: 27017
      MONGO_DATABASE: "Comment9"
    volumes:
      - ~/Comment9/pm2logs:/root/.pm2/logs
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - comment9-mongo-data:/data
  redis:
    image: redis:alpine
    restart: always
    volumes:
        - comment9-redis-data:/data
